### ISSUE TITLE
USER STORY: <Create a wireframe for landing page>

### ISSUE THREAD

**Issue by Declan444** [Declan444/Castlelost-Stud#3]
As a **designer** I can **use this wireframe** so that **design the landing page to the agreed design**

### Acceptance Criteria

- Acceptance Criteria 1: Agreed layout of landing page
- Acceptance Criteria 2: Agreed breakdown of this page
- Acceptance Criteria 3: All agreed sections of the page have been included

### Tasks
- [ ] Task 1: Agree a layout for the page
- [ ] Task 2: Use a wireframes program to design the page
- [ ] Task 3: Get approval that the design covers all aspects of approval
