### ISSUE TITLE
USER STORY: <Check calender>

### ISSUE THREAD

**Issue by Declan444** [Declan444/castlelost-stud#3]
As a **user** I can **see calendar**  so that **I can select a time slot for my lesson**

## Acceptance Criteria

- Acceptance Criteria 1: User should be able to see a list of available dates.
- Acceptance Criteria 2: User should be able to click on date and see available time slots for that date.
- Acceptance Criteria 3:

## Tasks

- [ ] Task 1: Design a monthly calendar showing days that are available
- [ ] Task 2: Design a day outline that shows time slots that are available
- [ ] Task 3: Make the monthly and day outlines interactive with a click
