### ISSUE TITLE
USER STORY: <Create a Readme file>

### ISSUE THREAD

**Issue by Declan444** [Declan444/Castlelost-Stud#4]
As a **developer** I can **read the file** so that **understand the program**

### Acceptance Criteria

- Acceptance Criteria 1: Readme file compiled
- Acceptance Criteria 2: Readme file contains all the relevant information
- Acceptance Criteria 3:

### Tasks
- [ ] Task 1: Create readme file
- [ ] Task 2: Have it checked to ensure it is acceptable
- [ ] Task 3: Sign off on this task
