### ISSUE TITLE
USER STORY: <Confirmation of lesson>

### ISSUE THREAD

**Issue by Declan444** [Declan444/castlelost-stud#4]
As a **user** I can **get confirmation of booking**  so that **get an email notification of confirmed booking**

## Acceptance Criteria

- Acceptance Criteria 1: Allow the user to click on the desired available time slot.
- Acceptance Criteria 2: Allow the user to get a confirmation notice and email that the booking has been confirmed.
- Acceptance Criteria 3: After the confirmation the booking should be recorded and the available time slots updated

## Tasks

- [ ] Task 1: Implement logic to handle the booking confirmation.
- [ ] Task 2: Create the requirement to send confirmation to the user via email and a confirmation notice on interface
- [ ] Task 3: Add functionality to update the database with the booking and associated user information.
