### ISSUE TITLE
USER STORY: Add a booking comment

### ISSUE THREAD

**Issue by Declan444** [Declan444/Castlelost-Stud#5]
As a **user** I can **send a request ** so that **I can make a booking**

### Acceptance Criteria

- Acceptance Criteria 1: User can enter a booking request
- Acceptance Criteria 2: User gets a response
- Acceptance Criteria 3: User can accept response

### Tasks
- [ ] Task 1: Allow user to enter the request
- [ ] Task 2: User will receive a follow up response
- [ ] Task 3: Booking time will be confirmed
